"""
NEX Config — Centrálna konfigurácia pre NEX Automat ekosystém.

Použitie:
    from nex_config.database import DB_HOST, DB_PORT
    from nex_config.timeouts import HTTP_DEFAULT_TIMEOUT_SECONDS
    from nex_config.services import QDRANT_URL
"""

from nex_config.database import (
    DB_HOST, DB_PORT, DB_USER, DB_PASSWORD,
    DB_NAME_MAIN, DB_NAME_STAGING, DB_NAME_RAG, DB_NAME_INVOICES,
    NEX_MIGRATION_DB_PORT,
)
from nex_config.services import (
    FASTAPI_URL, INVOICE_PIPELINE_URL, NEX_MANAGER_API_PORT,
    NEX_BRAIN_API_URL, NEX_BRAIN_API_PORT,
    QDRANT_URL, OLLAMA_URL,
    TEMPORAL_HOST, TEMPORAL_PORT,
    MARSO_WSDL_URL_PROD, MARSO_WSDL_URL_TEST,
)
from nex_config.timeouts import (
    HTTP_DEFAULT_TIMEOUT_SECONDS, LLM_REQUEST_TIMEOUT_SECONDS,
    HEALTH_CHECK_TIMEOUT_SECONDS, TELEGRAM_LLM_TIMEOUT_SECONDS,
    INGEST_EMBED_TIMEOUT_SECONDS, INGEST_UPSERT_TIMEOUT_SECONDS,
    PREFLIGHT_TIMEOUT_SECONDS,
    BACKUP_TIMEOUT_SECONDS, BACKUP_WRAPPER_TIMEOUT_SECONDS,
    SERVICE_CMD_TIMEOUT_SECONDS, HW_ANALYSIS_TIMEOUT_SECONDS,
    RAM_ANALYSIS_TIMEOUT_SECONDS,
    SERVICE_RESTART_DELAY_SECONDS, SERVICE_POLL_INTERVAL_SECONDS,
    DEPLOY_WAIT_DELAY_SECONDS, CHAT_LOADER_DELAY_SECONDS,
    INSTALLER_WAIT_DELAY_SECONDS,
    WORKFLOW_RETRY_INITIAL_SECONDS, WORKFLOW_RETRY_MAX_INTERVAL_SECONDS,
    ACTIVITY_TIMEOUT_SECONDS, PDF_ACTIVITY_TIMEOUT_SECONDS,
    SHORT_ACTIVITY_TIMEOUT_SECONDS,
)
from nex_config.limits import (
    MAX_RETRIES, DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE,
    PAB_BATCH_SIZE, RAG_BATCH_SIZE, EMBEDDING_MAX_CHARS,
)
from nex_config.paths import (
    NEX_ROOT_PATH, NEX_YEARACT_PATH, NEX_STORES_PATH,
    NEX_SQLITE_PATH, ARCHIVE_PATH,
    KNOWLEDGE_DIR, MANIFEST_PATH,
)
from nex_config.rag import (
    EMBEDDING_MODEL, RAG_CHUNK_SIZE, RAG_CHUNK_OVERLAP, RAG_MIN_CHUNK_SIZE,
)

# security.py NIE JE importovaný v __init__.py zámerne —
# obsahuje RuntimeError ak JWT_SECRET_KEY chýba.
# Importujte explicitne: from nex_config.security import JWT_SECRET_KEY
