"""Všetky timeouty, delays a intervaly. Jednotky vždy v názve."""

# HTTP timeouty
HTTP_DEFAULT_TIMEOUT_SECONDS = 30.0
LLM_REQUEST_TIMEOUT_SECONDS = 120.0
HEALTH_CHECK_TIMEOUT_SECONDS = 5.0
TELEGRAM_LLM_TIMEOUT_SECONDS = 60.0
INGEST_EMBED_TIMEOUT_SECONDS = 120
INGEST_UPSERT_TIMEOUT_SECONDS = 30
PREFLIGHT_TIMEOUT_SECONDS = 10

# Subprocess timeouty
BACKUP_TIMEOUT_SECONDS = 3600
BACKUP_WRAPPER_TIMEOUT_SECONDS = 7200
SERVICE_CMD_TIMEOUT_SECONDS = 30
HW_ANALYSIS_TIMEOUT_SECONDS = 120
RAM_ANALYSIS_TIMEOUT_SECONDS = 60

# Delays
SERVICE_RESTART_DELAY_SECONDS = 2
SERVICE_POLL_INTERVAL_SECONDS = 0.5
DEPLOY_WAIT_DELAY_SECONDS = 3
CHAT_LOADER_DELAY_SECONDS = 2
INSTALLER_WAIT_DELAY_SECONDS = 2

# Temporal workflow
WORKFLOW_RETRY_INITIAL_SECONDS = 5
WORKFLOW_RETRY_MAX_INTERVAL_SECONDS = 60
ACTIVITY_TIMEOUT_SECONDS = 300
PDF_ACTIVITY_TIMEOUT_SECONDS = 120
SHORT_ACTIVITY_TIMEOUT_SECONDS = 30
