/**
 * Auto-version from git tags.
 *
 * Reads `git describe --tags --long` and generates
 * src/renderer/src/version.ts with APP_VERSION and GIT_HASH exports.
 *
 * Version scheme:
 *   Tag v1.2.0 + 15 commits → version "1.2.15"
 *   Major.minor from tag, patch = tag patch + commits since tag.
 *
 * Windows compatible:
 *   - No --match glob (cmd.exe doesn't expand "v*" the same way)
 *   - Uses __dirname for output path (works from any CWD)
 *   - Uses git -C <repoRoot> so git always finds .git
 *   - Marks repoRoot as safe.directory
 *
 * Usage: node scripts/version.js  (run from nex-manager/ via npm pre-hooks)
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Repo root — monorepo root (apps/frontend/nex-manager/scripts → root)
const repoRoot = path.resolve(__dirname, '..', '..', '..', '..');

// Output path — always relative to this script, not CWD
const outFile = path.resolve(__dirname, '..', 'src', 'renderer', 'src', 'version.ts');

// Run git with explicit repo path and safe.directory to work on Windows CI
function git(cmd) {
  return execSync(
    `git -C "${repoRoot}" -c safe.directory="${repoRoot}" ${cmd}`,
    { encoding: 'utf-8' },
  ).trim();
}

function getVersion() {
  // Primary: git describe --tags --long (without --match to avoid Windows glob issues)
  try {
    const describe = git('describe --tags --long');
    const match = describe.match(/^v(\d+)\.(\d+)\.(\d+)-(\d+)-g([a-f0-9]+)$/);
    if (match) {
      const [, major, minor, patch, commits, hash] = match;
      const totalPatch = parseInt(patch) + parseInt(commits);
      return { version: `${major}.${minor}.${totalPatch}`, hash };
    }
  } catch (e) {
    console.error('[version] git describe failed:', e.message);
  }

  // Fallback: git tag -l + rev-list count
  try {
    const tags = git('tag -l').split('\n');
    const vTag = tags.filter(t => /^v\d+\.\d+\.\d+$/.test(t)).sort().pop();
    if (vTag) {
      const commits = git(`rev-list ${vTag}..HEAD --count`);
      const hash = git('rev-parse --short HEAD');
      const [, major, minor, patch] = vTag.match(/^v(\d+)\.(\d+)\.(\d+)$/);
      const totalPatch = parseInt(patch) + parseInt(commits);
      return { version: `${major}.${minor}.${totalPatch}`, hash };
    }
  } catch (e) {
    console.error('[version] fallback failed:', e.message);
  }

  // Last resort: just hash
  try {
    const hash = git('rev-parse --short HEAD');
    return { version: '0.0.0-dev', hash };
  } catch (e) {
    return { version: '0.0.0-dev', hash: 'unknown' };
  }
}

const { version, hash } = getVersion();
const content = `// Auto-generated by scripts/version.js — do not edit\nexport const APP_VERSION = '${version}';\nexport const GIT_HASH = '${hash}';\n`;
fs.writeFileSync(outFile, content);
console.log(`[version] ${version} (${hash})`);
